### ISSUE TITLE
Unauthenticated requests can be rate-limited by the API

### ISSUE THREAD

**Issue by wrboyce** [balena-io/open-balena-vpn#121]
We should probably grant a "guest level" service key for the VPN to use in-lieu of unauthenticated requests so we're not hit by stringent rate-limiting for (public URL) access checks.

**Comment by thgreasi** [comment]
Can't attach the issue in JF, so I'm manually pasting it here.
See: https://jel.ly.fish/4d31b491-0f94-4001-a930-d8fb7773d0a0
